language: go

go:
  - '1.8'
  - '1.9'
  - '1.10'

sudo: required

install:
  - sudo add-apt-repository ppa:pi-rho/dev -y
  - sudo apt-get update -q
  - sudo apt-get install vim-nox

before_script:
  - vim --version
  - go version
  - go env

script: sh ./themis.sh

# after_success:
#   # stop if latest commit is by myself, suppress infinite loop
#   - '[[ $(git log HEAD~..HEAD --oneline --grep "^\[auto-commit\]") ]] && exit 0'
#   # setup cross compiling environment
#   - make prepare
#   # cross compile
#   - make
#   # restore detached state
#   - git checkout $TRAVIS_BRANCH
#   # push when bin/ changes
#   - git add bin/
#   - git status
#   - git commit -m '[auto-commit] Latest binary.'
#   - '[ "$TRAVIS_BRANCH" == "master" ] && [ $GH_TOKEN ] && git push --quiet https://$GH_TOKEN@github.com/kamichidu/vim-hariti master 2>/dev/null'
