file
    : bundle*
    ;

bundle
    : 'use' repository
      bundle_option*
    | 'use' 'local' filepath
      local_bundle_option*
    ;

bundle_option
    : 'as' alias (',' alias)*
    | 'enable_if' String
    | 'depends' '('
        dependency*
      ')'
    | 'build' '{'
        build_script*
      '}'
    ;

build_script
    : 'on' 'windows' ('-' ShellScript)+
    | 'on' 'mac'     ('-' ShellScript)+
    | 'on' 'unix'    ('-' ShellScript)+
    | 'on' '*'       ('-' ShellScript)+
    ;

local_bundle_option
    : 'includes' '(' globexpr* ')'
    | 'excludes' '(' globexpr* ')'
    ;

repository
    : Identifier ('/' Identifier)?
    ;

dependency
    : repository
    ;

alias
    : Identifier
    ;

filepath
    : Path
    ;

globexpr
    : GlobExpr
    ;

Identifier
    : [a-zA-Z0-9.$_-]+
    ;

String
    : '(?:[^\']|\'\')'
    | "(?:[^\"]|\\\")"
    ;

GlobExpr
    : (?:\*{1,2}|\f)+
    ;

Path
    : \f+
    ;

ShellScript
    : [^\r\n]*
    ;
