file
    : bundle*
    ;

bundle
    : 'use' repository
      ('as' alias (',' alias)*)?
      ('enable_if' String)?
      ('depends' '('
        dependency*
      ')')?
    ;

repository
    : Identifier ('/' Identifier)?
    ;

dependency
    : repository
    ;

alias
    : Identifier
    ;

Identifier
    : [a-zA-Z0-9.$_-]+
    ;

String
    : '(?:[^\']|\'\')'
    | "(?:[^\"]|\\\")"
    ;
